const test1 = [
  {
    label: "Full Name",
    name: "full_name",
    type: "text",
    borderRadius: "20px",
    placeholder: "Enter your full name",
    icon: "fa:fa-user",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    rules: [
      { required: true, message: "Full Name is required" },
      { min: 4, message: "Minimum 4 characters required" },
    ],
    colSpan: { xs: 24, sm: 8, md: 12 },
  },
  {
    label: "Personal Email",
    name: "personal_email",
    type: "text",
    placeholder: "Enter personal email",
    icon: "fa:fa-envelope",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    rules: [
      { required: true, message: "Email is required" },
      {
        pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
        message: "Enter valid email",
      },
    ],
    colSpan: { xs: 24, sm: 12, md: 12 },
  },
  {
    label: "Birth Date",
    name: "birth_date",
    type: "date",
    placeholder: "Pick birth date",
    icon: "fa:fa-calendar-alt",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    colSpan: { xs: 24, sm: 12, md: 6 },
  },
  {
    label: "Available From",
    name: "available_from",
    type: "time",
    placeholder: "Select time",
    icon: "fa:fa-clock",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    colSpan: { xs: 24, sm: 12, md: 6 },
  },
  {
    label: "Country of Residence",
    name: "residence_country",
    type: "autocomplete",
    placeholder: "Choose country",
    options: [
      { label: "India", value: "IN" },
      { label: "Germany", value: "DE" },
      { label: "Australia", value: "AU" },
    ],
    icon: "fa:fa-globe",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    colSpan: { xs: 24, sm: 12, md: 12 },
  },
  {
    label: "State/Province",
    name: "state_province",
    type: "autocomplete",
    placeholder: "Choose state",
    options: [
      { label: "Andhra Pradesh", value: "AP" },
      { label: "Delhi", value: "DL" },
      { label: "Tamil Nadu", value: "TN" },
    ],
    icon: "fa:fa-map-marker",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    colSpan: { xs: 24, sm: 12, md: 12 },
  },
  {
    label: "Job Role",
    name: "job_role",
    type: "select",
    placeholder: "Select job role",
    options: ["Frontend Developer", "Backend Developer", "Designer", "Tester"],
    icon: "fa:fa-briefcase",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    colSpan: { xs: 24, sm: 12, md: 12 },
  },
  {
    label: "Profile Picture",
    name: "profile_pic",
    type: "upload",
    accept: "image/*",
    icon: "fa:fa-image",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    rules: [{ required: true, message: "Profile picture is required" }],
    colSpan: { xs: 24, sm: 12, md: 6 },
  },
  {
    label: "Agree to Terms",
    name: "agree_terms",
    type: "checkbox",
    icon: "fa:fa-check-square",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    rules: [{ required: true, message: "You must agree to terms" }],
    colSpan: { xs: 24, sm: 12, md: 6 },
  },
  {
    label: "Enable Notifications",
    name: "enable_notifications",
    type: "switch",
    icon: "fa:fa-bell",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    colSpan: { xs: 24, sm: 12, md: 6 },
  },
  {
    label: "Preferred Contact",
    name: "preferred_contact",
    type: "radio",
    options: ["Email", "Phone", "Telegram"],
    icon: "fa:fa-comments",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    colSpan: { xs: 24, sm: 12, md: 6 },
  },
  {
    label: "About Yourself",
    name: "about_you",
    type: "textarea",
    placeholder: "Write about yourself...",
    rows: 5,
    icon: "fa:fa-info-circle",
    iconStyle: { fontSize: "16px", color: "#e67e22", margin: "0 6px" },
    colSpan: { xs: 24, sm: 24, md: 24 },
  },
];
export default test1;
