const test3 = [
  {
    label: "fullname",
    name: "fullname",
    placeholder: "Enter your fullname",
    type: "text",
    icon: "fa:fa-user",
    colSpan: { md: 12, xs: 6, sm: 6 },
    rules: [{ required: false, message: "enter your name" }],
  },
  {
    label: "Email",
    name: "Email",
    placeholder: "Enter your Email",
    type: "email",
    icon: "fa:fa-user",
    rules: [
      { required: true, message: "enter your Email" },
      {
        pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
        message: "enter valid email number",
      },
    ],
  },
  {
    label: "Country",
    name: "Country",
    placeholder: "Enter your Country name",
    type: "text",
    icon: "fa:fa-user",
    rules: [{ required: true, message: "enter your name" }],
  },
  {
    label: "what is your profession",
    name: "profession",
    placeholder: "Enter your profession",
    type: "select",
    options: [
      { label: "student", value: "student" },
      { label: "worker", value: "worker" },
    ],
    icon: "fa:fa-user",
    rules: [{ required: true, message: "enter your name" }],
  },
  {
    label: "work role",
    name: "role",
    placeholder: "select or type work work",
    type: "autocomplete",
    options: [
      { label: "engineer", value: "engineer" },
      { label: "developer", value: "developer" },
      { label: "react", value: "react" },
      { label: "angular", value: "angular" },
    ],
  },
  {
    label: "Start date",
    name: "date",
    placeholder: "Enter your Start date",
    type: "date",
    icon: "fa:fa-user",
    rules: [{ required: false, message: "enter your Start date" }],
  },
  {
    label: "End date",
    name: "Enddate",
    placeholder: "Enter your End date",
    type: "date",
    icon: "fa:fa-user",
    rules: [{ required: false, message: "enter your End date" }],
  },
  {
    name: "worktimings",
    label: "worktimings",
    placeholder: "Enter your worktimings",
    type: "time",
    icon: "fa:fa-user",
    rules: [{ required: false, message: "enter your worktimings" }],
  },
  {
    label: "enter your phone",
    name: "phone",
    placeholder: "Enter your enter your phone",
    type: "phone",
    icon: "fa:fa-user",
    rules: [
      { required: false, message: "enter your enter your phone" },
      { min: 10, message: "mininmum 10 digit number" },
      { max: 12, message: "maximum 12 digit number" },
    ],
  },
  {
    label: "enter your photo",
    name: "photo",
    placeholder: "Enter your enter your photo",
    type: "upload",
    icon: "fa:fa-user",
    rules: [{ required: true, message: "enter your enter your photo" }],
  },
];
export default test3;
